---
- name: giphy-build
  hosts: 127.0.0.1
  vars:
    build_name: "{{ lookup('env', 'BUILD_NAME') }}"
    workspace: "{{ lookup('env', 'WORKSPACE') }}"
  tasks:
    - name: "create logs dir"
      command: mkdir {{ workspace }}/logs

    - name: "npm install"
      npm:
        path: "{{ workspace }}"

    - name: "package app"
      command: tar --exclude=".git" --exclude=".gitignore" -zcvf {{ build_name }} -C {{ workspace }} .

    - name: "update latest build"
      command: "{{ item }}"
      with_items:
        - mkdir -p {{ workspace }}/builds/latest
        - find {{ workspace }}/builds/latest -type f -execdir mv {} {{ workspace }}/builds/ \;
        - mv {{ build_name }} {{ workspace }}/builds/latest

- name: giphy-deploy
  hosts: 10.10.10.190
  remote_user: jenkins
  vars:
    deploy_path: "/home/jenkins"
    app_dir: app
    app_entrypoint: app.js
  tasks:
    - name: "create deploy path"
      shell: "{{ item }}"
      with_items:
        - test -d {{ deploy_path }}/{{ app_dir }} && rm -rf {{ deploy_path }}/{{ app_dir }}
        - mkdir {{ deploy_path }}/{{ app_dir }}

    - name: "Get build package"
      copy:
        src: "{{ workspace }}/builds/latest/{{ build_name }}"
        dest: "{{ deploy_path }}"

    - name: "unpackage"
      unarchive:
        src:  "{{ deploy_path }}/{{ build_name }}"
        dest: "{{ deploy_path }}/{{ app_dir }}"
        remote_src: yes


    - name: "install pm2"
      npm:
        name: pm2
        global: yes

    - name: "run node app"
      shell: "{{ item }}"
      with_items:
        - cd "{{ deploy_path }}/{{ app_dir }}"
        - pm2 stop all && pm2 start {{ app_entrypoint }}
